# Generated by Django 5.2.7 on 2025-10-14 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='სახელი')),
                ('email', models.EmailField(max_length=254, verbose_name='ელ. ფოსტა')),
                ('phone', models.CharField(max_length=50, verbose_name='ტელეფონის ნომერი')),
                ('message', models.TextField(blank=True, null=True, verbose_name='შეტყობინება')),
                ('submission_type', models.CharField(choices=[('PRODUCT', 'პროდუქტის შეძენა'), ('CONTACT', 'საკონტაქტო ფორმა')], max_length=10, verbose_name='ფორმის ტიპი')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='გაგზავნის დრო')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='პროდუქტი')),
            ],
            options={
                'verbose_name': 'გაგზავნილი ფორმა',
                'verbose_name_plural': 'გაგზავნილი ფორმები',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
