# Generated by Django 5.2.7 on 2025-10-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='email',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='message',
        ),
        migrations.AddField(
            model_name='submission',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='მისამართი'),
        ),
        migrations.AddField(
            model_name='submission',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='კომენტარი'),
        ),
    ]
