# Generated by Django 5.2.7 on 2025-10-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_submission_email_remove_submission_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='address',
            field=models.CharField(default='მისამართი მითითებული არ არის', max_length=255, verbose_name='მისამართი'),
        ),
    ]
