# Generated by Django 5.2.7 on 2025-10-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_submission_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='რაოდენობა'),
        ),
    ]
