# Generated by Django 5.2.7 on 2025-10-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='დასახელება')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ფასი')),
                ('description', models.TextField(verbose_name='აღწერა')),
                ('image', models.URLField(verbose_name='სურათის URL')),
                ('category', models.CharField(choices=[('სამუშაო სივრცე', 'სამუშაო სივრცე'), ('აუდიო', 'აუდიო'), ('აქსესუარები', 'აქსესუარები'), ('გაჯეტები', 'გაჯეტები')], max_length=50, verbose_name='კატეგორია')),
                ('popularity', models.PositiveIntegerField(default=0, verbose_name='პოპულარობა')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='დამატების თარიღი')),
            ],
            options={
                'verbose_name': 'პროდუქტი',
                'verbose_name_plural': 'პროდუქტები',
                'ordering': ['-popularity'],
            },
        ),
    ]
