# Generated by Django 5.2.7 on 2025-10-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='მთავარ გვერდზე ჩვენება'),
        ),
    ]
