# Generated by Django 5.2.7 on 2025-10-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='product',
            name='homepage_placement',
            field=models.CharField(choices=[('NONE', 'არ არის ნაჩვენები'), ('FEATURED', 'რჩეული პროდუქტი'), ('SLIDER', 'სლაიდერი')], default='NONE', max_length=10, verbose_name='განთავსება მთავარ გვერდზე'),
        ),
    ]
