# Generated by Django 5.2.7 on 2025-10-14 03:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'კატეგორია', 'verbose_name_plural': 'კატეგორიები'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'პროდუქტი', 'verbose_name_plural': 'პროდუქტები'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='შექმნის თარიღი'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='შექმნის თარიღი'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_image',
            field=models.ImageField(blank=True, help_text='რეკომენდებული ზომა: 1920x800 პიქსელი', null=True, upload_to='sliders/', verbose_name='სლაიდერის სურათი'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='კატეგორია'),
        ),
        migrations.AlterField(
            model_name='product',
            name='homepage_placement',
            field=models.CharField(choices=[('NONE', 'არ არის ნაჩვენები'), ('SLIDER', 'სლაიდერი'), ('FEATURED', 'რჩეული პროდუქტი')], default='NONE', max_length=10, verbose_name='განთავსება მთავარ გვერდზე'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='რეკომენდებული ზომა: 800x800 პიქსელი', upload_to='products/', verbose_name='პროდუქტის სურათი'),
        ),
        migrations.AlterField(
            model_name='product',
            name='popularity',
            field=models.PositiveIntegerField(default=0, verbose_name='პოპულარულობა'),
        ),
    ]
